routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::resource('posts', 'PostController');
Route::get('/', 'HomeController@index')->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model{
    //

    protected $fillable = [
        'user_id','title','content','is_draft','is_members_only','posted_at'
    ];

    public function user(){
        return $this->hasOne('App\Models\User','id','user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
use Auth;

class HomeController extends Controller{
    /**
     * Display a listing of the users' posts.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $userId = (isset(Auth::user()->id)) ? Auth::user()->id : 0;
        $posts = Post::where('user_id',$userId)->get();
        return view('home',compact('posts'));
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Redirect;
use Auth;

class PostController extends Controller{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $posts = Post::where('posted_at','<',Carbon::now()->toDateTimeString())->where('is_draft',0)->where('is_members_only',0)->paginate(10);
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        // Validate posted form data
        $request->validate([
            'title' => 'required|string|max:100',
            'content' => 'required|string|max:50,000',
            'posted_at' => 'required',
        ]);
        if (!isset($request->is_draft)) {
            $request['is_draft'] = '0';
        }
        $request['user_id'] = Auth::user()->id;
        $request['posted_at'] = str_replace('T', ' ', $request->posted_at);
        
        // Create and save post with validated data
        $post = Post::create($request->all());

        // Redirect the user to the created post with a success message
        return redirect(route('home'))->with('message', 'Post created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post){
        return view('posts.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post){
        return view('posts.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post){
        // Validate posted form data
        $request->validate([
            'title' => 'required|string|max:100',
            'content' => 'required|string|max:50,000',
            'posted_at' => 'required',
        ]);
        if (!isset($request->is_draft)) {
            $request['is_draft'] = '0';
        }
        $request['user_id'] = Auth::user()->id;
        $request['posted_at'] = str_replace('T', ' ', $request->posted_at);

        // Update Post with validated data
        $post->update($request->all());

        // Redirect the user to the created post woth an updated message
        return redirect(route('home'))->with('message', 'Post updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post){
        if($post->delete()) { 
            return Redirect::route('home')->with('message', 'Post deleted.');
        }
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if ($message = Session::get('message'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button> 
                    <strong>{{ $message }}</strong>
            </div>
            @endif
            {{-- If logged-in user has posts, show all posts written by the user. --}}
            <h3>Your Posts</h3>
            @foreach($posts as $key => $post)
                <div class="card mt-3">
                    <div class="card-header"><a href="{{url('posts/'.$post->id)}}">{{ $post->title }}</a></div>
                    <div class="card-body">
                        @if($post->is_draft)
                            <span class="badge badge-secondary">Draft</span>
                        @else
                            <span class="badge badge-primary">Published</span>
                        @endif
                        @if($post->is_members_only)
                            <span class="badge badge-success">Members Only</span>
                        @endif
                        <span class="ml-2">Posted: {{ date('Y-m-d',strtotime($post->posted_at)) }}</span> / <span>Updated: {{ date('Y-m-d',strtotime($post->updated_at)) }}</span>
                        <div class="mt-3">
                            <a href="{{url('posts/'.$post->id)}}">Detail</a> /
                            <a href="{{ route('posts.edit', $post->id) }}">Edit</a> /
                            <form action="{{ route('posts.destroy',$post->id) }}" method="POST" class="d-inline">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-link p-0 border-0 text-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach

            @if(Auth::check() && $posts->isEmpty())
                {{-- If logged-in user doesn't have posts, show sentence below. --}}
                <p>You have no posts yet. Create a new post <a href="{{route('posts.create')}}">here</a>.</p>
            @endif

            @guest
                {{-- If guest users, show sentence below. --}}
                <p>Please login <a href="{{ route('login') }}">here</a>.</p>
                <p>If you don't have an account, register <a href="{{ route('register') }}">here</a>.</p>
            @endguest

        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Laravel Test</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Laravel Test
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('posts.index') }}">All Posts</a>
                        </li>
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h3>Create a New Post</h3>
            <div class="card mt-3">
                <div class="card-body">
                    <form method="POST" action="{{route('posts.store')}}">
                        @csrf
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" value="{{ old('title') }}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" id="title" required>
                            @if ($errors->has('title'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="content">Content</label>
                            <textarea class="form-control{{ $errors->has('content') ? ' is-invalid' : '' }}" name="content" id="content" rows="3" required>{{ old('content') }}</textarea>
                            @if ($errors->has('content'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('content') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="posted_at">Post Date</label>
                            <input type="datetime-local" name="posted_at" value="{{ old('posted_at') }}" class="form-control{{ $errors->has('posted_at') ? ' is-invalid' : '' }}" id="posted_at" required>
                            @if ($errors->has('posted_at'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('posted_at') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" name="is_draft" value="1" class="form-check-input" id="is_draft" {{ old('is_draft') ? 'checked' : '' }}>
                            <label class="form-check-label" for="is_draft">Draft</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" name="is_members_only" value="1" class="form-check-input" id="is_members_only" {{ old('is_members_only') ? 'checked' : '' }}>
                            <label class="form-check-label" for="is_members_only">Members Only</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h3>Edit Post</h3>
            <div class="card mt-3">
                <div class="card-body">
                    <form method="POST" action="{{route('posts.update', $post->id)}}">
                        @csrf
                        @method('patch')
                        <div class="form-group">
                            <label for="title">Title</label>
                            <input type="text" name="title" value="{{ old('title') ?? $post->title }}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" id="title" required>
                            @if ($errors->has('title'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="content">Content</label>
                            <textarea class="form-control{{ $errors->has('content') ? ' is-invalid' : '' }}" name="content" id="content" rows="3" required>{{ old('content') ?? $post->content }}</textarea>
                            @if ($errors->has('content'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('content') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="posted_at">Post Date</label>
                            <input type="datetime-local" name="posted_at" value="{{ old('posted_at') ?? str_replace(' ', 'T', $post->posted_at) }}" class="form-control{{ $errors->has('posted_at') ? ' is-invalid' : '' }}" id="posted_at" required>
                            @if ($errors->has('posted_at'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('posted_at') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" name="is_draft" value="1" class="form-check-input" id="is_draft" @if(old('is_draft') ?? $post->is_draft) checked="" @endif>
                            <label class="form-check-label" for="is_draft">Draft</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" name="is_members_only" value="1" class="form-check-input" id="is_members_only" @if(old('is_members_only') ?? $post->is_members_only) checked="" @endif>
                            <label class="form-check-label" for="is_members_only">Members Only</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h3>All Posts</h3>
            @include('posts.item')
            <div class="mt-5">
                {!! $posts->links() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/item.blade.php
@foreach($posts as $key => $post)
<div class="card mt-3">
    <div class="card-header"><a href="{{url('posts/'.$post->id)}}">{{ $post->title }}</a></div>
    <div class="card-body d-flex justify-content-between">
        <span>{{ $post->user->name }}</span>
        <span>{{ date('Y-m-d',strtotime($post->posted_at)) }}</span>
    </div>
</div>
@endforeach

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h3>Post Detail</h3>
            <div class="card mt-3">
                <div class="card-header">{{ $post->title }}</div>
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <span>{{ $post->user->name }}</span>
                        <span>{{ date('Y-m-d',strtotime($post->posted_at)) }}</span>
                    </div>
                    <hr>
                    <div>
                        {!! $post->content !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection